# remember "rake asset:packager:build_all"

---
javascripts:
- base:
  - jquery

  #- jquery-ui
  - jquery.textarea
  #- jquery.autocomplete
  #- jquery.autoSuggest
  #- jquery.notifyBar


  #- jquery.ui.sortable
  #- jquery.cookie



- mobile:
  - jquery
  - modules/editor

- welcome:
  - jcarousellite_1.0.1
  - jquery.cycle.all.latest
  - jquery.easing.1.1
  #- jquery.effects.core
  #- jquery.effects.bounce
  #- jquery.marquee
  #- jquery.scroll

- show:
  - jquery.tools.min
  - jquery-ui
  - jquery.textarea
  - showdown
  - highlight/prettify
  - components/search
  - application
  - modules/sessions
  - modules/index_item
  - jquery.autocomplete
  - jquery.autoSuggest
  - modules/members
  - modules/move_group
  - modules/single/item
  - modules/show_item

  #- jHtmlArea




  - jquery.autovideo

  - modules/new_item
  - modules/index_welcome
  - modules/show_user
  - modules/index_group
  - modules/index_user
  - modules/retag
  - modules/tags_item
  - jquery.lightbox
  - mediaplayer/jwplayer
  - modules/editor


- login:
  - openid/js/jquery.openid.min



stylesheets:
- base:
  #- jquery-ui
  - jquery-lightbox
  - compiled/application
  - prettify
  - ../javascripts/openid/css/style



